---
- name: Конфигурировать правила предупреждений в Prometheus
  hosts: localhost
  become: yes

  tasks:
    - name: Копировать файл правил предупреждений
      copy:
        src: /путь/к/вашему/файлу/alert.rules.yml
        dest: /etc/prometheus/alert.rules.yml
