---
- name: Установка SELinux в разрешающий режим (фактически отключив его)
  command: setenforce 0
  ignore_errors: yes
  failed_when: false

- name: Изменение директивы SELinux в файле /etc/sysconfig/selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: Остановить и отключить firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

