---
- name: Установка Kubernetes Docker
  hosts: masters, workers
  remote_user: root
  become: yes
  gather_facts: yes
 
  tasks:
    # Добавляем загрузку модулей ядра
    - include_tasks: tasks/load_kernel_modules.yaml
 
    - name: Запустить задачу для отключения SELinux
      include_tasks: tasks/disable_selinux.yaml
 
    - name: Установить необходимые пакеты для Rocky Linux 8
      dnf:
        name:
          - dnf-plugins-core
          - tar
          - tmux
          - wget
          - curl
          - tree
          - vim
          - nano
          - mc
          - git
          - iproute-tc
        state: present
 
    - name: Выполнить dnf -y update
      shell: dnf -y update
 
    - name: Добавить репозиторий Docker CE
      shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
 
    - name: Установить containerd
      dnf:
        name: containerd
        state: present
 
    - name: Установить Docker CE
      dnf:
        name: docker-ce
        state: present
        enablerepo: docker-ce-stable
 
    - name: Создать конфигурационный файл для Docker CE
      copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"]
          }
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
 
    - name: Включить и запустить сервис Docker
      service:
        name: docker
        state: started
        enabled: yes
 
    - name: Добавляем репозиторий Kubernetes YUM
      yum_repository:
        name: kubernetes
        description: Kubernetes Repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
 
    - name: Установить Kubernetes components с указанием версий
      dnf:
        name:
          - kubelet-1.27.4-0.x86_64
          - kubeadm-1.27.4-0.x86_64
          - kubectl-1.27.4-0.x86_64
          - kubernetes-cni-1.2.0-0.x86_64
        state: present
 
    - name: Включить и запустить сервис kubelet
      service:
        name: kubelet
        state: started
        enabled: yes
 
    - name: Отключить swap
      shell: "swapoff -a"
      ignore_errors: yes
 
    - name: Закомментировать строку с пунктом монтирования swap в /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/mapper/rl-swap'
        line: '# /dev/mapper/rl-swap     none                    swap    defaults        0 0'
 
    - name: Добавить параметры ядра в файл /etc/sysctl.d/k8s.conf
      copy:
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0644'
 
    - name: Перезапустить kubelet
      service:
        name: kubelet
        state: restarted
        enabled: yes
 
    - name: Перезапустить containerd
      service:
        name: containerd
        state: restarted
        enabled: yes
 
    - name: Убедиться, что kubelet запущен и включен
      service:
        name: kubelet
        state: started
        enabled: yes
 
    - name: Убедиться, что containerd запущен и включен
      service:
        name: containerd
        state: started
        enabled: yes
